# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('vote_time', models.DateField()),
                ('vote_selection', models.CharField(choices=[('1', 'Happy'), ('2', 'Vomit'), ('3', 'Bored')], max_length=1)),
            ],
        ),
    ]
