# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webservice.Dish'),
        ),
    ]
